CREATE TABLE USERS {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USERNAME TEXT,
	PASSWORD TEXT,
	EMAIL TEXT
},

CREATE TABLE TEAMS {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME TEXT
},

CREATE TABLE TEAM_MEMBERS {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT,
	TEAM_ID INT,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID) ON DELETE CASCADE
},

CREATE TABLE CALENDAR_EVENTS {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT,
	EVENT_TYPE INT,
	START_DATE INT,
	END_DATE INT,
	NAME TEXT,
	DESCRIPTION TEXT,
	PRIORITY INT,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
},

CREATE TABLE EVENT_TYPE {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME TEXT
},

CREATE TABLE TASK {
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TEAM_ID INT,
	MEMBER_ID INT,
	ESTIMATED_TIME INT,
	TOOK_TIME INT,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID) ON DELETE CASCADE
}